title: Fabio Buono
email: fabio.buono@ymail.com
description: >- 
  Theme for my personal site on github

baseurl: ""
url: "" # full URL 

theme: fabiobuono

siti: [LoremLab.Com, MarianneCode.Com, YouTube.Com, Medium.Com, Scotch.Io, Hackr.Io]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:title

include: ["_pages", "_elenchi_categorie"]

